program: conv_ssl/train.py
project: ULMProjection
description: Train on encoder output (no kmeans) for bidirectional encoders.
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  encoder.type: 
     values: [wavlm_base+, hubert_base]
  encoder.output_layer: 
     values: [6, -1]
  tier2.num_layers:
    values: [1, 2, 4]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--gpus"
  - "-1"
  - "--dont_log_model"
  - "--patience"
  - "10"
  - "--max_epochs"
  - "10"
  - "--batch_size"
  - "70"
  - "--limit_train_batches"
  - "5000"
  - "--limit_val_batches"
  - "500"
  - "--quantizer.n_codes"
  - "0"
  - "--tier1.num_layers"
  - "0"
  - "--tier2.num_heads"
  - "4"
  - "--tier2.dim"
  - "256"
  - ${args}
