theme: jekyll-theme-cayman
title: How Much does Prosody Help Turn-taking?
description: Investigations using Voice Activity Projection Models
baseurl: "conv_ssl"
url: "https://erikekstedt.github.io"

# Super slow to compile without exclusion
exclude:
  - artifacts
  - assets
  - conv_ssl
  - lightning_logs
  - node_modules
  - runs
  - tests
  - wandb
