encoder:
  use: 0
  pretrained: true
  output_layer: 6
  type: hubert_base
  frame_hz: 50 # Hz

quantizer:
  use: 0
  type: kmeans # VQ
  vector_path: dataset_units/hubert_base/k_vectors.pt
  n_codes: 100
  dim: 768
