encoder:
  pretrained: true
  output_layer: 1
  sample_rate: 16000
  type: wav2vec

quantizer:
  type: kmeans # VQ
  vector_path: null
  n_codes: 0

ulm:
  type: 'transformer'
  dim: 512
  num_layers: 0
  num_heads: 4
  use_pos_emb: 1
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

ar:
  type: 'transformer'
  dim: 512
  num_layers: 1
  num_heads: 4
  use_pos_emb: 1
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

vad_cond:
  pre_ulm: true
  post_ulm: false
  vad_history: true
  vad_history_bins: 5

vad_class_prediction:
  regression: false
  n_classes: 256
  bin_times: [.2, .4, .6, .8]
  vad_threshold: 0.5
  pred_threshold: 0.5
  event_min_context: 1.0
  event_min_duration: 0.15
  event_horizon: 1.0
  event_start_pad: 0.05
  event_target_duration: 0.10

optimizer:
  alpha: 0.6
  learning_rate: 3.63e-4
  betas: [0.9, 0.999]
  weight_decay: 0.001
