encoder:
  use: 0
  pretrained: true
  output_layer: 6
  type: hubert_base
  frame_hz: 50 # Hz

quantizer:
  use: 0
  type: kmeans # VQ
  vector_path: dataset_units/hubert_base/k_vectors.pt
  n_codes: 100
  dim: 256

tier1:
  type: 'transformer'
  dim: 32
  num_layers: 1
  num_heads: 1
  use_pos_emb: 1
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

tier2:
  use: 1
  type: 'transformer'
  dim: 32
  num_layers: 1
  num_heads: 1
  use_pos_emb: 0
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

vad_class_prediction:
  n_classes: 256
  bin_sizes: [10, 20, 30, 40]

optimizer:
  learning_rate: 3.63e-4
  betas: [0.9, 0.999]
  weight_decay: 0.001
