encoder:
  pretrained: true
  output_layer: 6
  type: wav2vec2_base

quantizer:
  type: kmeans # VQ
  vector_path: null
  n_codes: 100

tier1:
  type: 'transformer'
  dim: 768
  num_layers: 4
  num_heads: 4
  use_pos_emb: 1
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

tier2:
  type: 'transformer'
  dim: 768
  num_layers: 1
  num_heads: 4
  use_pos_emb: 0
  abspos: true
  sizeSeq: 1024
  dff_k: 3
  dropout: 0.1

vad_class_prediction:
  regression: false
  n_classes: 256
  bin_sizes: [10, 20, 30, 40]

optimizer:
  alpha: 0.6
  learning_rate: 3.63e-4
  betas: [0.9, 0.999]
  weight_decay: 0.001
