# vim:ft=dockerfile
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime
WORKDIR /workspace
RUN apt-get update
RUN apt-get install git g++ sox -y

# torchaudio does not want to cooperate... this takes time but works
RUN pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

# CPCAudio
WORKDIR /dependencies
RUN git clone https://github.com/facebookresearch/CPC_audio.git
WORKDIR /dependencies/CPC_audio
RUN git checkout b98a1bdf1fe9ea219816db7a6c28115d404a3510
RUN pip install cython
RUN python setup.py develop
