program: conv_ssl/train_disk.py
project: VPModel
description: Train directly on encoder output (no AR)
method: grid
metric:
  name: val_f1_weighted
  goal: maximize
parameters:
  ar.dim:
    values: [64, 128, 256]
  ar.dropout:
    values: [0.2, 0.4, 0.6]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--gpus"
  - "-1"
  - "--conf"
  - "conv_ssl/config/model.yaml"
  - "--ar.num_layers"
  - "4"
  - "--batch_size"
  - "50"
  - "--max_epochs"
  - "30"
  - ${args}
