program: conv_ssl/train.py
project: ULMProjection
description: Train directly on encoder output (no AR)
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  encoder.type: 
     values: [wav2vec, vq_wav2vec, hubert_base, wavlm_base+]
  tier2.num_layers:
    values: [1, 2]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--gpus"
  - "-1"
  - "--dont_log_model"
  - "--patience"
  - "5"
  - "--max_epochs"
  - "5"
  - "--batch_size"
  - "70"
  - "--limit_train_batches"
  - "2000"
  - "--limit_val_batches"
  - "500"
  - "--quantizer.n_codes"
  - "0"
  - "--tier1.num_layers"
  - "0"
  - "--tier2.num_heads"
  - "4"
  - "--tier2.dim"
  - "256"
  - ${args}
