program: conv_ssl/train_on_units.py
project: ULMProjection
description: tier1 layers
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  tier1.dim:
    values: [64, 256, 768]
  tier1.num_layers:
    values: [1, 4]
  tier2.num_layers:
    values: [1, 2]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--gpus"
  - "-1"
  - "--dont_log_model"
  - "--patience"
  - "5"
  - "--max_epochs"
  - "5"
  - "--batch_size"
  - "10"
  - "--limit_train_batches"
  - "1000"
  - "--limit_val_batches"
  - "200"
  - "--tier2.num_heads"
  - "4"
  - "--conf" 
  - "conv_ssl/config/ulm_wavlm.yaml"
  - "--data_root" 
  - "dataset_units/wavlm_base+"
  - ${args}
