defaults:
  - model: model
  - events: events
  - trainer: trainer
  - data: data

seed: 1
verbose: false

wandb:
  project: 'VAP'
  dont_log_model: true


optimizer:
  alpha: 0.6
  learning_rate: 3.63e-4
  betas: [0.9, 0.999]
  weight_decay: 0.001

early_stopping:
  patience: 3
  monitor: 'val_loss'
  mode: 'min'

checkpoint:
  monitor: 'val_loss'
  mode: 'min'

hydra:
  run:
    dir: runs
